### ISSUE TITLE
Deepl Translate context menu no longer display in TB 115

### ISSUE THREAD

**Issue by HugoGresse** [itagagaki/DeepL-Selected-Text#8]
Hi,

In Thunderbird 115, the Translate button using Deepl is no longer displayed. 
![image](https://github.com/itagagaki/DeepL-Selected-Text/assets/662377/e7ad80a5-dbd3-409f-8be5-2da266397cec)

**Comment by itagagaki** [comment]
It may be that you not have selected any text yet. Once the text is selected and the context menu is displayed, a button would be at the bottom of the menu.

**Comment by HugoGresse** [comment]
I did select the text, I have been using the app since 2021. I tried restarting Thunderbird but it did not fix this.

**Comment by HugoGresse** [comment]
ah, did not fill the initial issue correctly, my bad. 
Mac OS Ventura 13.0.1. 

But I think the issue is related to the "Thunderbird Conversations" plugin which display the email content below the email list. The translate button still appear in the full email window.

**Comment by itagagaki** [comment]
In the regular Thunderbird message window there are many items in the context menu, but in the Conversations message view I only see Copy and Paste and Select All. I think you should ask the developer of Thunderbird Conversations why this is. I have no idea.

One workaround is to display messages in a new tab (classic view).
Another workaround is to use keyboard shortcuts instead of the context menu.

**Comment by HugoGresse** [comment]
Yes you're right, closing this as unrelated to this extension. 
Thanks!
